Ais\PimpinanProdiBundle\Entity\PimpinanProdi:
 type: entity
 table: pimpinan_prodi
 id:
  id: 
   type: integer
   generator: { strategy: AUTO }
 fields:
  user_id:
   type: integer
  prodi_id:
   type: integer
  posisi:
   type: string
  is_active:
   type: boolean
   nullable: true
  is_delete:
   type: boolean
   nullable: true
