<?php

namespace Ais\PimpinanProdiBundle\Repository;

/**
 * PimpinanProdiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PimpinanProdiRepository extends \Doctrine\ORM\EntityRepository
{
}
